import { Router } from "express";
import { randomUUID } from "node:crypto";
import { allowRoles } from "../middleware/auth.middleware.js";
import { operationsRepository } from "../repositories/operations.repository.js";

const router=Router(),now=()=>new Date().toISOString();
const required={projects:["client_id","name"],jobs:["project_id","title","design_type"],designers:["name"],revisions:["design_job_id","feedback"],proofs:["design_job_id"],payments:["project_id","amount"]};
const data={projects:[],jobs:[],designers:[],revisions:[],proofs:[],payments:[]};

router.get("/reports/summary",async(_req,res,next)=>{try{const [projects,jobs,payments,designers]=operationsRepository.enabled?await Promise.all([operationsRepository.list("projects"),operationsRepository.list("jobs"),operationsRepository.list("payments"),operationsRepository.list("designers")]):[data.projects,data.jobs,data.payments,data.designers];res.json({data:{activeProjects:projects.filter(x=>x.status==="ACTIVE").length,openJobs:jobs.filter(x=>!["COMPLETED","CANCELLED"].includes(x.status)).length,pendingPayments:payments.filter(x=>x.status!=="PAID").reduce((sum,x)=>sum+Number(x.amount||0),0),teamUtilization:designers.length?Math.round(designers.reduce((sum,x)=>sum+Number(x.capacity||0),0)/designers.length):0}})}catch(error){next(error)}});
router.get("/:module",async(req,res,next)=>{try{const records=data[req.params.module];if(!records)return res.status(404).json({message:"Module not found"});res.json({data:{records:operationsRepository.enabled?await operationsRepository.list(req.params.module):records}})}catch(error){next(error)}});
router.post("/:module",allowRoles("ADMIN"),async(req,res,next)=>{try{const records=data[req.params.module];if(!records)return res.status(404).json({message:"Module not found"});const missing=required[req.params.module].filter(key=>req.body[key]===undefined||String(req.body[key]).trim()==="");if(missing.length)return res.status(422).json({message:`Required fields: ${missing.join(", ")}`});if(operationsRepository.enabled)return res.status(201).json({data:{record:await operationsRepository.create(req.params.module,req.body)}});const record={id:randomUUID(),...req.body,created_at:now()};records.unshift(record);res.status(201).json({data:{record}})}catch(error){next(error)}});
router.put("/:module/:id",allowRoles("ADMIN"),async(req,res,next)=>{try{const records=data[req.params.module];if(!records)return res.status(404).json({message:"Module not found"});if(operationsRepository.enabled){const record=await operationsRepository.update(req.params.module,req.params.id,req.body);return record?res.json({data:{record}}):res.status(404).json({message:"Record not found"})}const index=records.findIndex(x=>x.id===req.params.id);if(index<0)return res.status(404).json({message:"Record not found"});records[index]={...records[index],...req.body,id:req.params.id,updated_at:now()};res.json({data:{record:records[index]}})}catch(error){next(error)}});
router.delete("/:module/:id",allowRoles("ADMIN"),async(req,res,next)=>{try{const records=data[req.params.module];if(!records)return res.status(404).json({message:"Module not found"});if(operationsRepository.enabled){const record=await operationsRepository.remove(req.params.module,req.params.id);return record?res.json({data:{success:true}}):res.status(404).json({message:"Record not found"})}const index=records.findIndex(x=>x.id===req.params.id);if(index<0)return res.status(404).json({message:"Record not found"});records.splice(index,1);res.json({data:{success:true}})}catch(error){if(error.code==="23503")return res.status(409).json({message:"This record is still used by another workflow. Remove dependent records first."});next(error)}});
export default router;
