import express from "express";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import path from "node:path";
import { fileURLToPath } from "node:url";
import dashboardRouter from "./routes/dashboard.routes.js";
import authRouter from "./routes/auth.routes.js";
import clientRouter from "./routes/client.routes.js";
import { requireAuth } from "./middleware/auth.middleware.js";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const app = express();
app.disable("x-powered-by");
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use(express.static(root, { extensions: ["html"] }));
app.get("/api/health", (_req, res) => res.json({ data: { status: "ok", service: "cgdm-api" } }));
app.use("/api/auth", authRouter);
app.use("/api/dashboard", requireAuth, dashboardRouter);
app.use("/api/v1/clients", requireAuth, clientRouter);
app.use("/api", (_req, res) => res.status(404).json({ message: "API route not found" }));
app.use((error, _req, res, _next) => { if(!error.status)console.error(error); res.status(error.status||500).json({ message:error.status?error.message:"An unexpected error occurred", errors:error.errors }); });
