import express from "express";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import path from "node:path";
import { fileURLToPath } from "node:url";
import dashboardRouter from "./routes/dashboard.routes.js";
import authRouter from "./routes/auth.routes.js";
import clientRouter from "./routes/client.routes.js";
import operationsRouter from "./routes/operations.routes.js";
import filesRouter from "./routes/files.routes.js";
import supportRouter from "./routes/support.routes.js";
import portalRouter from "./routes/portal.routes.js";
import { requireAuth } from "./middleware/auth.middleware.js";
import { requestLogger } from "./middleware/request-logger.js";
import { databaseEnabled, query } from "./config/database.js";
import { supabaseEnabled } from "./config/supabase.js";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const app = express();
app.disable("x-powered-by");
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use(requestLogger);
app.use(express.static(root, { extensions: ["html"] }));
app.get("/api/health", async (_req, res) => {let database=databaseEnabled?"checking":"not_configured";if(databaseEnabled)try{await query("SELECT 1");database="healthy"}catch{database="unhealthy"}const healthy=database!=="unhealthy";res.status(healthy?200:503).json({data:{status:healthy?"ok":"degraded",service:"cgdm-api",dependencies:{database,supabase:supabaseEnabled?"configured":"not_configured"}}})});
app.use("/api/portal",portalRouter);
app.use("/api/auth", authRouter);
app.use("/api/dashboard", requireAuth, dashboardRouter);
app.use("/api/v1/clients", requireAuth, clientRouter);
app.use("/api/v1/operations", requireAuth, operationsRouter);
app.use("/api/v1/files", requireAuth, filesRouter);
app.use("/api/v1/support", requireAuth, supportRouter);
app.use("/api", (_req, res) => res.status(404).json({ message: "API route not found" }));
app.use((error, _req, res, _next) => { const uploadError=error.name==="MulterError"||error.message==="Unsupported file type";if(!error.status&&!uploadError)console.error(error);res.status(error.status|| (uploadError?400:500)).json({message:error.status||uploadError?error.message:"An unexpected error occurred",errors:error.errors}); });
